{- 
   Problem 29
   How many distinct terms are in the sequence generated by a^b for 2 ≦ a ≦ 100 and 2 ≦ b ≦ 100?
   
   http://projecteuler.net/problem=29
 -}

import qualified Data.Map as M

main = print $ solve 100

solve :: Integer -> Int
solve n = length $ f nums M.empty
    where nums = [ a^b | a <- [2..n], b <- [2..n] ]
          f [] d = M.keys d
          f (x:xs) d
            | M.member x d = f xs d
            | otherwise    = f xs (M.insert x True d)
